# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
gazebo_ros_control/pid_gains:
    joint_1: {p: 100.0, i: 1, d: 1.0}
    joint_2: {p: 100.0, i: 1, d: 1.0}
    joint_3: {p: 100.0, i: 1, d: 1.0}
    joint_4: {p: 100.0, i: 1, d: 1.0}
    joint_5: {p: 100.0, i: 1, d: 1.0}
    joint_6: {p: 100.0, i: 1, d: 1.0}
